-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQge1eckM+i/5tiWXQK
NJkGLnjsRk6STi8mOkQzvnqKp5WgCgYIKoZIzj0DAQehRANCAARECFPUXObRwfAb
XtMzeOg3kIw5AQ40zk4dysaqZ4qtZKWeqis8Lc3FdyXbrdRu+TxX6UsZDZiEKFKm
t2JA8gcy
-----END PRIVATE KEY-----